com:
  mqtt:
    inbound:
      url: tcp://ip:1883
      clientId: familyServerIn
      topics: topic1,topic2
    outbound:
      urls: tcp://ip:1883
      clientId: familyServerOut
      topic: topic1
